### ISSUE TITLE
Post updated version of the plugin npmjs.com

### ISSUE THREAD

**Issue by rinodrummer** [leafiy/parcel-plugin-sw-precache2#3]
@leafiy, I know you're busy, but when you have a bit of free time, please update the plugin on https://npmjs.com.

Thanks in advice.

**Comment by leafiy** [comment]
@rinodrummer Thanks for your pull requests.I have updated it on NPM.

**Comment by rinodrummer** [comment]
It's a pleasure to make this plugin work better.

I pushed a new pull request to fix a bug!

If you want, you can add me as contributor on npmjs.com so I'll provide autonomously to update the version.
